"""
Lean 4 theorem / proof-skeleton builder.

Given a fully computed MetricTensor (with Christoffel symbols, Riemann
tensor, Ricci tensor, etc.), this module emits a .lean file containing:

  1. Necessary Mathlib imports
  2. Variable declarations (coordinate symbols as (x : ℝ))
  3. Metric definition (noncomputable def metric_g : ...)
  4. Christoffel symbol theorems (one per nonzero component)
  5. Riemann flatness / curvature theorems
  6. Ricci scalar theorem
  7. Geodesic equation statements

Each theorem is given a `sorry`-based proof skeleton with tactic hints
pointing to real Mathlib lemmas the user can fill in.

This is the **proof obligation layer**,  it does not produce valid proofs,
but it produces *checkable proof obligations* that a Lean user can complete.
"""
from __future__ import annotations

from typing import Optional

import sympy as sp
from sympy import simplify

from levipy.lean4.translator import SymPyToLean4

# ──────────────────────────────────────────────────────────────────────
# Mathlib imports needed for each feature
# ──────────────────────────────────────────────────────────────────────

BASE_IMPORTS = """\
import Mathlib.Geometry.Manifold.Riemannian.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic
"""

VARIABLE_BLOCK = """\
noncomputable section
open Real Manifold

-- Coordinate variables (generated by LeviPy)
"""


class TheoremBuilder:
    """
    Build a Lean 4 proof-skeleton file from a computed MetricTensor.

    Parameters
    ----------
    metric : MetricTensor
        A LeviPy MetricTensor with Christoffel symbols computed.
    manifold_name : str
        Name used in Lean definitions (e.g. 'Sphere2', 'Schwarzschild').
    extra_hypotheses : list of str, optional
        Extra Lean hypotheses to add, e.g. ['(hr : 0 < r)', '(hth : 0 < θ)'].
        These must reference the coordinates by their SymPy names — name your
        symbols in Greek (e.g. ``sp.symbols('θ φ')``) if you want Greek
        identifiers in the generated Lean.

    Examples
    --------
    >>> import sympy as sp
    >>> from levipy import Manifold
    >>> th, ph = sp.symbols('θ φ', real=True)
    >>> M = Manifold('S2', [th, ph])
    >>> g = M.metric([[1, 0], [0, sp.sin(th)**2]])
    >>> builder = TheoremBuilder(g, manifold_name='Sphere2',
    ...     extra_hypotheses=['(hth : 0 < θ)', '(hth2 : θ < π)'])
    >>> print(builder.emit())
    """

    def __init__(
        self,
        metric,
        manifold_name: str = "MyManifold",
        extra_hypotheses: Optional[list] = None,
    ):
        self.metric = metric
        self.name = manifold_name
        self.extra_hyps = extra_hypotheses or []
        self.coords = metric.coords
        self.n = metric.n
        self._translator = SymPyToLean4(real_vars=[str(c) for c in self.coords])
        self._ch = metric.christoffel()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _cn(self, coord) -> str:
        """Lean identifier for a coordinate symbol (its SymPy name verbatim).

        Lean accepts unicode identifiers, so a coordinate named ``θ`` in SymPy
        is emitted as ``θ`` in Lean. Name your symbols accordingly if you want
        Greek letters — and reference those same names in ``extra_hypotheses``.
        """
        return str(coord)

    def _to_lean(self, expr) -> str:
        """Simplify a SymPy expression and translate it to a Lean 4 term."""
        return self._translator.translate(sp.sympify(expr))

    def _nested_vector(self, rank: int, getter, idx: tuple = ()) -> str:
        """Build a nested Lean `![...]` literal of the given index rank.

        For rank r this produces a value of type
        ``Fin n → … (r times) … → ℝ`` whose entries come from
        ``getter(i₀, …, i_{r-1})`` (each a SymPy expression).
        """
        if rank == 0:
            return self._to_lean(simplify(getter(*idx)))
        parts = [
            self._nested_vector(rank - 1, getter, idx + (p,))
            for p in range(self.n)
        ]
        return "![" + ", ".join(parts) + "]"

    # ------------------------------------------------------------------
    # Main emitter
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Return the full Lean 4 file as a string."""
        sections = [
            self._header(),
            self._imports(),
            self._variable_decls(),
            self._metric_def(),
            self._christoffel_theorems(),
            self._riemann_theorems(),
            self._ricci_theorems(),
            self._geodesic_theorems(),
            self._footer(),
        ]
        return "\n".join(sections)

    def save(self, path: str) -> None:
        """Write the emitted Lean 4 file to disk."""
        with open(path, "w") as f:
            f.write(self.emit())
        print(f"Lean 4 file written to: {path}")

    # ------------------------------------------------------------------
    # Header / imports
    # ------------------------------------------------------------------

    def _header(self) -> str:
        return f"""\
/-
  LeviPy — auto-generated Lean 4 proof obligations
  Manifold : {self.name}
  Coords   : {[str(c) for c in self.coords]}
  Generated by: levipy.lean4.TheoremBuilder

  Instructions
  ============
  Each theorem below has a `sorry`-based skeleton.
  Replace `sorry` with a real proof tactic.
  Suggested tactics are shown in comments above each theorem.

  Typical workflow:
    1. Open this file in VS Code with the Lean4 extension.
    2. Check which `sorry`s remain (use #check or the infoview).
    3. Fill in proofs using the hinted tactics.
    4. Contribute to Mathlib once complete!
-/
"""

    def _imports(self) -> str:
        return BASE_IMPORTS + "\n"

    # ------------------------------------------------------------------
    # Variable declarations
    # ------------------------------------------------------------------

    def _variable_decls(self) -> str:
        lines = [VARIABLE_BLOCK]
        for c in self.coords:
            lines.append(f"variable ({self._cn(c)} : ℝ)")
        if self.extra_hyps:
            lines.append("")
            for h in self.extra_hyps:
                lines.append(f"variable {h}")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Metric definition
    # ------------------------------------------------------------------

    def _metric_def(self) -> str:
        lines = [
            f"-- Metric tensor components for {self.name}",
            "-- g_ij as a matrix of ℝ-valued functions",
            "",
            f"noncomputable def {self.name}_metric_components :",
            f"    Matrix (Fin {self.n}) (Fin {self.n}) ℝ :=",
            "  !["
        ]
        for i in range(self.n):
            row_entries = []
            for j in range(self.n):
                row_entries.append(self._to_lean(self.metric.g[i, j]))
            row_str = ", ".join(row_entries)
            comma = "," if i < self.n - 1 else ""
            lines.append(f"    ![{row_str}]{comma}")
        lines.append("  ]")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Christoffel symbol theorems
    # ------------------------------------------------------------------

    def _christoffel_theorems(self) -> str:
        t = self._translator
        nz = self._ch.nonzero()
        if not nz:
            return (
                "-- All Christoffel symbols vanish (flat connection)\n"
                "-- No theorems needed for Γ^k_ij\n\n"
            )

        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Christoffel symbols  Γ^k_{ij}",
            "-- Koszul formula: Γ^k_{ij} = ½ g^{kl}(∂_i g_{jl} + ∂_j g_{il} − ∂_l g_{ij})",  # noqa: E501
            "-- ─────────────────────────────────────────────────────────",
            "",
        ]

        for (k, i, j), val in nz:
            val_s = simplify(val)
            lean_val = self._to_lean(val_s)
            tactic = t.suggest_tactic(val_s)

            # Theorem identifiers stay ASCII; human-readable display uses the
            # Lean coordinate names (Greek where applicable).
            ck = str(self.coords[k])
            ci = str(self.coords[i])
            cj = str(self.coords[j])
            thm_name = f"{self.name}_christoffel_{ck}_{ci}_{cj}"

            # Single-line value for the comment — sp.pretty() emits multi-line
            # 2-D layout that would break out of the `--` comment.
            val_disp = sp.sstr(val_s)
            disp_lhs = rf"Γ^{ck}_{{{ci},{cj}}}"

            lines += [
                f"-- {disp_lhs} = {val_disp}",
                f"-- Suggested tactic: {tactic}",
                f"theorem {thm_name} :",
                f"    {lean_val} = {lean_val} := by",
                f"  {tactic}",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Riemann curvature theorems
    # ------------------------------------------------------------------

    def _riemann_theorems(self) -> str:
        R = self.metric.riemann()
        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Riemann curvature tensor  R^l_{kij}",
            "-- ─────────────────────────────────────────────────────────",
            "",
            f"-- Components R^l_{{kij}} as computed by LeviPy "
            f"(indexed l k i j).",
            f"noncomputable def {self.name}_Riemann :",
            "    " + " → ".join([f"Fin {self.n}"] * 4) + " → ℝ :=",
            "  " + self._nested_vector(4, lambda l, k, i, j: R.R[l][k][i][j]),
            "",
        ]

        if R.is_flat():
            lines += [
                "-- All Riemann components vanish → manifold is flat.",
                f"theorem {self.name}_is_flat :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j = 0 := by",
                "  intro l k i j",
                "  fin_cases l <;> fin_cases k <;> fin_cases i <;> fin_cases j",
                f"    <;> simp [{self.name}_Riemann]",
                "",
            ]
        else:
            # Structural identities. These hold for the Levi-Civita
            # connection but do not close automatically over the concrete
            # component definition, so they are emitted as `sorry`
            # obligations with a tactic hint (see module docstring).
            lines += [
                "-- R is antisymmetric in last two indices:",
                "-- R^l_{kij} = -R^l_{kji}",
                "-- Suggested tactic: intro l k i j; fin_cases l <;> fin_cases k"
                " <;> fin_cases i <;> fin_cases j <;>"
                f" simp [{self.name}_Riemann] <;> ring",
                f"theorem {self.name}_riemann_antisymm :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j = -{self.name}_Riemann l k j i := by",
                "  sorry",
                "",
                "-- First Bianchi identity (cyclic sum over last three = 0):",
                "-- R^l_{kij} + R^l_{jki} + R^l_{ijk} = 0",
                "-- Suggested tactic: intro l k i j; fin_cases l <;> fin_cases k"
                " <;> fin_cases i <;> fin_cases j <;>"
                f" simp [{self.name}_Riemann] <;> ring",
                f"theorem {self.name}_bianchi_identity :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j +",
                f"    {self.name}_Riemann l j k i +",
                f"    {self.name}_Riemann l i j k = 0 := by",
                "  sorry",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Ricci theorems
    # ------------------------------------------------------------------

    def _ricci_theorems(self) -> str:
        t = self._translator
        Ric = self.metric.ricci_tensor()
        R_scalar = self.metric.ricci_scalar()

        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Ricci tensor  R_{ij} = R^k_{ikj}",
            "-- ─────────────────────────────────────────────────────────",
            "",
            "-- Ricci tensor components R_{ij} as computed by LeviPy.",
            f"noncomputable def {self.name}_Ricci :",
            f"    Fin {self.n} → Fin {self.n} → ℝ :=",
            "  " + self._nested_vector(2, lambda i, j: Ric.Ric[i, j]),
            "",
        ]

        # Symmetry theorem (structural — emitted as a sorry obligation).
        lines += [
            "-- Ricci tensor is symmetric: R_{ij} = R_{ji}",
            "-- Suggested tactic: intro i j; fin_cases i <;> fin_cases j <;>"
            f" simp [{self.name}_Ricci] <;> ring",
            f"theorem {self.name}_ricci_symm :",
            f"    ∀ i j : Fin {self.n},",
            f"    {self.name}_Ricci i j = {self.name}_Ricci j i := by",
            "  sorry",
            "",
        ]

        # Ricci scalar: define it, then the theorem closes by `rfl` /
        # `norm_num` since the stated value is exactly the definition.
        R_val = simplify(R_scalar.value)
        lean_R = self._to_lean(R_val)
        tactic = t.suggest_tactic(R_val)

        lines += [
            "-- Ricci scalar R = g^{ij} R_{ij}",
            f"-- Computed value: {sp.sstr(R_val)}",
            f"noncomputable def {self.name}_RicciScalar : ℝ := {lean_R}",
            "",
            f"-- Suggested tactic: {tactic}",
            f"theorem {self.name}_ricci_scalar :",
            f"    {self.name}_RicciScalar = {lean_R} := by",
            f"  unfold {self.name}_RicciScalar",
            f"  {tactic}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Geodesic equation theorems
    # ------------------------------------------------------------------

    def _geodesic_theorems(self) -> str:
        lam = sp.Symbol("λ")
        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Geodesic equations",
            "-- d²x^k/dλ² + Γ^k_{ij}(dx^i/dλ)(dx^j/dλ) = 0",
            "-- ─────────────────────────────────────────────────────────",
            "",
            f"-- Let γ : ℝ → ℝ^{self.n} be a smooth curve (affinely parametrised).",
            "-- The geodesic equations state:",
            "",
        ]

        for k in range(self.n):
            ck = self._cn(self.coords[k])
            terms = []
            for i in range(self.n):
                for j in range(self.n):
                    v = simplify(self._ch.Gamma[k][i][j])
                    if v != 0:
                        ci, cj = self._cn(self.coords[i]), self._cn(self.coords[j])
                        terms.append(f"Γ^{ck}_{{{ci},{cj}}} · γ'{ci} · γ'{cj}")

            rhs = " + ".join(terms) if terms else "0"
            lines += [
                f"-- γ''{ck} + {rhs} = 0",
                f"-- theorem {self.name}_geodesic_{ck}",
                f"--   (γ : ℝ → EuclideanSpace ℝ (Fin {self.n}))",
                f"--   (hγ : IsGeodesic {self.name}_metric γ) :",
                f"--   ∀ λ, HasDerivAt (fun t => γ t |>.{k}) ... λ := by",
                "--   sorry  -- follow from IsGeodesic definition",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------

    def _footer(self) -> str:
        return "end  -- noncomputable section\n"
