"""
Lean 4 theorem / proof-skeleton builder.

Given a fully computed MetricTensor (with Christoffel symbols, Riemann
tensor, Ricci tensor, etc.), this module emits a .lean file containing:

  1. Necessary Mathlib imports
  2. Variable declarations (coordinate symbols as (x : ℝ))
  3. Metric definition (noncomputable def metric_g : ...)
  4. Christoffel symbol theorems (one per nonzero component)
  5. Riemann flatness / curvature theorems
  6. Ricci scalar theorem
  7. Geodesic equation statements

Each theorem is given a `sorry`-based proof skeleton with tactic hints
pointing to real Mathlib lemmas the user can fill in.

This is the **proof obligation layer**,  it does not produce valid proofs,
but it produces *checkable proof obligations* that a Lean user can complete.
"""
from __future__ import annotations

from typing import Optional

import sympy as sp
from sympy import simplify

from levipy.lean4.translator import SymPyToLean4

# ──────────────────────────────────────────────────────────────────────
# Mathlib imports needed for each feature
# ──────────────────────────────────────────────────────────────────────

BASE_IMPORTS = """\
import Mathlib.Geometry.Manifold.Riemannian.Basic
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic
"""

VARIABLE_BLOCK = """\
noncomputable section
open Real Manifold

-- Coordinate variables (generated by LeviPy)
"""


class TheoremBuilder:
    """
    Build a Lean 4 proof-skeleton file from a computed MetricTensor.

    Parameters
    ----------
    metric : MetricTensor
        A LeviPy MetricTensor with Christoffel symbols computed.
    manifold_name : str
        Name used in Lean definitions (e.g. 'Sphere2', 'Schwarzschild').
    extra_hypotheses : list of str, optional
        Extra Lean hypotheses to add, e.g. ['(hr : 0 < r)', '(hth : 0 < θ)'].

    Examples
    --------
    >>> import sympy as sp
    >>> from levipy import Manifold
    >>> th, ph = sp.symbols('theta phi', real=True)
    >>> M = Manifold('S2', [th, ph])
    >>> g = M.metric([[1, 0], [0, sp.sin(th)**2]])
    >>> builder = TheoremBuilder(g, manifold_name='Sphere2',
    ...     extra_hypotheses=['(hth : 0 < θ)', '(hth2 : θ < π)'])
    >>> print(builder.emit())
    """

    def __init__(
        self,
        metric,
        manifold_name: str = "MyManifold",
        extra_hypotheses: Optional[list] = None,
    ):
        self.metric = metric
        self.name = manifold_name
        self.extra_hyps = extra_hypotheses or []
        self.coords = metric.coords
        self.n = metric.n
        self._translator = SymPyToLean4(real_vars=[str(c) for c in self.coords])
        self._ch = metric.christoffel()

    # ------------------------------------------------------------------
    # Main emitter
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Return the full Lean 4 file as a string."""
        sections = [
            self._header(),
            self._imports(),
            self._variable_decls(),
            self._metric_def(),
            self._christoffel_theorems(),
            self._riemann_theorems(),
            self._ricci_theorems(),
            self._geodesic_theorems(),
            self._footer(),
        ]
        return "\n".join(sections)

    def save(self, path: str) -> None:
        """Write the emitted Lean 4 file to disk."""
        with open(path, "w") as f:
            f.write(self.emit())
        print(f"Lean 4 file written to: {path}")

    # ------------------------------------------------------------------
    # Header / imports
    # ------------------------------------------------------------------

    def _header(self) -> str:
        return f"""\
/-
  LeviPy — auto-generated Lean 4 proof obligations
  Manifold : {self.name}
  Coords   : {[str(c) for c in self.coords]}
  Generated by: levipy.lean4.TheoremBuilder

  Instructions
  ============
  Each theorem below has a `sorry`-based skeleton.
  Replace `sorry` with a real proof tactic.
  Suggested tactics are shown in comments above each theorem.

  Typical workflow:
    1. Open this file in VS Code with the Lean4 extension.
    2. Check which `sorry`s remain (use #check or the infoview).
    3. Fill in proofs using the hinted tactics.
    4. Contribute to Mathlib once complete!
-/
"""

    def _imports(self) -> str:
        return BASE_IMPORTS + "\n"

    # ------------------------------------------------------------------
    # Variable declarations
    # ------------------------------------------------------------------

    def _variable_decls(self) -> str:
        lines = [VARIABLE_BLOCK]
        for c in self.coords:
            lines.append(f"variable ({c} : ℝ)")
        if self.extra_hyps:
            lines.append("")
            for h in self.extra_hyps:
                lines.append(f"variable {h}")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Metric definition
    # ------------------------------------------------------------------

    def _metric_def(self) -> str:
        t = self._translator
        lines = [
            f"-- Metric tensor components for {self.name}",
            "-- g_ij as a matrix of ℝ-valued functions",
            "",
            f"noncomputable def {self.name}_metric_components :",
            f"    Matrix (Fin {self.n}) (Fin {self.n}) ℝ :=",
            "  !["
        ]
        for i in range(self.n):
            row_entries = []
            for j in range(self.n):
                entry = simplify(self.metric.g[i, j])
                row_entries.append(t.translate(entry))
            row_str = ", ".join(row_entries)
            comma = "," if i < self.n - 1 else ""
            lines.append(f"    ![{row_str}]{comma}")
        lines.append("  ]")
        lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Christoffel symbol theorems
    # ------------------------------------------------------------------

    def _christoffel_theorems(self) -> str:
        t = self._translator
        nz = self._ch.nonzero()
        if not nz:
            return (
                "-- All Christoffel symbols vanish (flat connection)\n"
                "-- No theorems needed for Γ^k_ij\n\n"
            )

        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Christoffel symbols  Γ^k_{ij}",
            "-- Koszul formula: Γ^k_{ij} = ½ g^{kl}(∂_i g_{jl} + ∂_j g_{il} − ∂_l g_{ij})",  # noqa: E501
            "-- ─────────────────────────────────────────────────────────",
            "",
        ]

        for (k, i, j), val in nz:
            val_s = simplify(val)
            lean_val = t.translate(val_s)
            tactic = t.suggest_tactic(val_s)

            ck = str(self.coords[k])
            ci = str(self.coords[i])
            cj = str(self.coords[j])
            thm_name = f"{self.name}_christoffel_{ck}_{ci}_{cj}"

            # LaTeX comment for human readability
            latex_lhs = rf"Γ^{ck}_{{{ci},{cj}}}"

            lines += [
                f"-- {latex_lhs} = {sp.pretty(val_s)}",
                f"-- Suggested tactic: {tactic}",
                f"theorem {thm_name} :",
                f"    {lean_val} = {lean_val} := by",
                f"  {tactic}",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Riemann curvature theorems
    # ------------------------------------------------------------------

    def _riemann_theorems(self) -> str:
        R = self.metric.riemann()
        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Riemann curvature tensor  R^l_{kij}",
            "-- ─────────────────────────────────────────────────────────",
            "",
        ]

        if R.is_flat():
            lines += [
                "-- All Riemann components vanish → manifold is flat.",
                f"theorem {self.name}_is_flat :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j = 0 := by",
                "  intro l k i j",
                "  fin_cases l <;> fin_cases k <;> fin_cases i <;> fin_cases j",
                f"    <;> simp [{self.name}_Riemann]",
                "",
            ]
        else:
            # Emit symmetry / anti-symmetry as theorems
            lines += [
                "-- R is antisymmetric in last two indices:",
                "-- R^l_{kij} = -R^l_{kji}",
                f"theorem {self.name}_riemann_antisymm :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j = -{self.name}_Riemann l k j i := by",
                "  intro l k i j",
                f"  simp [{self.name}_Riemann]",
                "  ring",
                "",
                "-- Second Bianchi identity (cyclic sum = 0):",
                "-- R^l_{kij} + R^l_{jki} + R^l_{ijk} = 0",
                f"theorem {self.name}_bianchi_identity :",
                f"    ∀ l k i j : Fin {self.n},",
                f"    {self.name}_Riemann l k i j +",
                f"    {self.name}_Riemann l j k i +",
                f"    {self.name}_Riemann l i j k = 0 := by",
                "  intro l k i j",
                f"  simp [{self.name}_Riemann]",
                "  ring",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Ricci theorems
    # ------------------------------------------------------------------

    def _ricci_theorems(self) -> str:
        t = self._translator
        Ric = self.metric.ricci_tensor()
        R_scalar = self.metric.ricci_scalar()

        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Ricci tensor  R_{ij} = R^k_{ikj}",
            "-- ─────────────────────────────────────────────────────────",
            "",
        ]

        # Symmetry theorem
        lines += [
            "-- Ricci tensor is symmetric: R_{ij} = R_{ji}",
            f"theorem {self.name}_ricci_symm :",
            f"    ∀ i j : Fin {self.n},",
            f"    {self.name}_Ricci i j = {self.name}_Ricci j i := by",
            "  intro i j",
            f"  simp [{self.name}_Ricci]",
            "  ring",
            "",
        ]

        # Ricci scalar theorem
        R_val = simplify(R_scalar.value)
        lean_R = t.translate(R_val)
        tactic = t.suggest_tactic(R_val)

        lines += [
            "-- Ricci scalar R = g^{ij} R_{ij}",
            f"-- Computed value: {R_val}",
            f"-- Suggested tactic: {tactic}",
            f"theorem {self.name}_ricci_scalar :",
            f"    {self.name}_RicciScalar = {lean_R} := by",
            f"  unfold {self.name}_RicciScalar",
            f"  {tactic}",
            "",
        ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Geodesic equation theorems
    # ------------------------------------------------------------------

    def _geodesic_theorems(self) -> str:
        lam = sp.Symbol("λ")
        lines = [
            "-- ─────────────────────────────────────────────────────────",
            "-- Geodesic equations",
            "-- d²x^k/dλ² + Γ^k_{ij}(dx^i/dλ)(dx^j/dλ) = 0",
            "-- ─────────────────────────────────────────────────────────",
            "",
            f"-- Let γ : ℝ → ℝ^{self.n} be a smooth curve (affinely parametrised).",
            "-- The geodesic equations state:",
            "",
        ]

        for k in range(self.n):
            ck = str(self.coords[k])
            terms = []
            for i in range(self.n):
                for j in range(self.n):
                    v = simplify(self._ch.Gamma[k][i][j])
                    if v != 0:
                        ci, cj = str(self.coords[i]), str(self.coords[j])
                        terms.append(f"Γ^{ck}_{{{ci},{cj}}} · γ'{ci} · γ'{cj}")

            rhs = " + ".join(terms) if terms else "0"
            lines += [
                f"-- γ''{ck} + {rhs} = 0",
                f"-- theorem {self.name}_geodesic_{ck}",
                f"--   (γ : ℝ → EuclideanSpace ℝ (Fin {self.n}))",
                f"--   (hγ : IsGeodesic {self.name}_metric γ) :",
                f"--   ∀ λ, HasDerivAt (fun t => γ t |>.{k}) ... λ := by",
                "--   sorry  -- follow from IsGeodesic definition",
                "",
            ]

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Footer
    # ------------------------------------------------------------------

    def _footer(self) -> str:
        return "end  -- noncomputable section\n"
